name: Run tests

on:
  push:
    branches: [test-CI-Newman]
 

jobs:

  api-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # run the npm build command (not used in our project)
    - run: npm run build --if-present
       # install pm2 so we can run our node.js
      # based backend without blocking the terminal
    - run: npm install -g pm2
    - run: npm run init-adm
    - run: pm2 start "npm run init-sds"
    
      # install newman globally so we can run
      # postman collections
    - run: npm install -g newman
   
      # run our api tests
    - run: cd test-rest-api && npm install -g newman && newman run teacher_newman.json